# Generated by Django 4.1.3 on 2022-11-05 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='active',
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
